- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SymfonyCastsVerifyEmailExtension.php
- src/Exception/ExpiredSignatureException.php
- src/Exception/VerifyEmailExceptionInterface.php
- src/Generator/VerifyEmailTokenGenerator.php
- src/Model/VerifyEmailSignatureComponents.php
- src/Model/VerifyEmailUrlComponents.php
- src/SymfonyCastsVerifyEmailBundle.php
- src/Util/VerifyEmailQueryUtility.php
- src/Util/VerifyEmailUrlUtility.php
- src/VerifyEmailHelper.php
- src/VerifyEmailHelperInterface.php
> fix class headers

- composer.json
@jrushlow I couldn't figure out if this one was important or not.
> removing http-foundation conflict

- README.md
- src/Exception/InvalidSignatureException.php
- src/Exception/VerifyEmailExceptionInterface.php
- src/Exception/WrongEmailVerifyException.php
- src/VerifyEmailHelper.php
- src/VerifyEmailHelperInterface.php
- tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
- tests/FunctionalTests/VerifyEmailHelperFunctionalTest.php
- tests/UnitTests/VerifyEmailHelperTest.php
Instead of the mix of a bool return type and also an exception.
> Changing the helper check method to always throw an exception

- .github/workflows/ci.yml
> run ci every 12 hours

- tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
- tests/FunctionalTests/VerifyEmailHelperFunctionalTest.php
- tests/IntegrationTests/VerifyEmailBundleAutowireTest.php
- tests/IntegrationTests/VerifyEmailServiceDefinitionTest.php
- tests/UnitTests/Exception/VerifyEmailExceptionTest.php
- tests/UnitTests/Util/VerifyEmailQueryTest.php
- tests/UnitTests/VerifyEmailHelperTest.php
- tests/VerifyEmailTestKernel.php
- mark ~`internal`~ & `final` where needed
- fixed missing author
> fix test headers where required

- .github/workflows/ci.yml
- Implement Symfony 5.1.*
- Change from Symfony dev-master to dev-main
> update versions of symfony to test against in CI

- CHANGELOG.md
- src/Resources/translations/VerifyEmailBundle.de.xlf
> Enhancement: Add German translations

- CHANGELOG.md
Used the wrong url to the PR :)
> Minor url fix in CHANGELOG.md

- CHANGELOG.md
- src/Resources/translations/VerifyEmailBundle.pt.xlf
adds Portuguese translations from https://github.com/SymfonyCasts/reset-password-bundle/pull/158 - Thanks @larzuk91
> add Portuguese translations

- CHANGELOG.md
- src/Resources/translations/VerifyEmailBundle.it.xlf
adds Italian translations from https://github.com/SymfonyCasts/reset-password-bundle/pull/160 - thanks @cristoforocervino
> add Italian translations

- src/Resources/translations/VerifyEmailBundle.tr.xlf
> Add Turkish Translations

- src/Resources/translations/VerifyEmailBundle.fi.xlf
sourced from https://github.com/SymfonyCasts/reset-password-bundle/pull/169
> [translations] add Finnish translations

- src/Resources/translations/VerifyEmailBundle.hu.xlf
Sourced from https://github.com/SymfonyCasts/reset-password-bundle/pull/196
Credit and Thanks to @1ed
> [translations] add Hungarian translations

- CHANGELOG.md
Howdy Verifiers!
This small release adds Hungarian translations.
*January 31st, 2022*
- [#95](https://github.com/symfonycasts/verify-email-bundle/pull/95) - [translations] add Hungarian translations - *@jrushlow*
Changes: https://github.com/SymfonyCasts/verify-email-bundle/compare/v1.7.0...v1.8.0
Enjoy!
*January 31st, 2022*
- [#95](https://github.com/symfonycasts/verify-email-bundle/pull/95) - [translations] add Hungarian translations - *@jrushlow*
> [release] v1.8.0

- src/Resources/translations/VerifyEmailBundle.uk.xlf
> Translate exception reasons to Ukrainian

- src/Resources/translations/VerifyEmailBundle.ru.xlf
> Translate exception reasons to Russian

- src/Resources/translations/VerifyEmailBundle.fr.xlf
> Translate exception reasons to French

- src/Resources/translations/VerifyEmailBundle.ro.xlf
Hello,
I needed a Romanian 🇷🇴  translation for this bundle, made one in the project I'm working on and I thought it would be nice to share with the community. 
Thanks for this bundle! It gave me structure over something I was doing over and over again but never standardised.
> romanian translation

- CHANGELOG.md
*March 8th, 2022*
- [#111](https://github.com/symfonycasts/verify-email-bundle/pull/111) - romanian translation - *@redecs*
- [#110](https://github.com/symfonycasts/verify-email-bundle/pull/110) - Add Spanish translations to exceptions - *@larzuk91*
_Generated by Git Released_
> [git-released] v1.10.0

- src/Resources/translations/VerifyEmailBundle.ca.xlf
Added catalan translations to bundle
> Add catalan translations

- src/Resources/translations/VerifyEmailBundle+intl-icu.nl.xlf
- src/Resources/translations/VerifyEmailBundle.cs.xlf
- src/Resources/translations/VerifyEmailBundle.de.xlf
- src/Resources/translations/VerifyEmailBundle.en.xlf
- src/Resources/translations/VerifyEmailBundle.es.xlf
- src/Resources/translations/VerifyEmailBundle.it.xlf
- src/Resources/translations/VerifyEmailBundle.pl.xlf
- src/Resources/translations/VerifyEmailBundle.pt.xlf
- src/Resources/translations/VerifyEmailBundle.ro.xlf
- src/Resources/translations/VerifyEmailBundle.ru.xlf
- src/Resources/translations/VerifyEmailBundle.sk.xlf
- src/Resources/translations/VerifyEmailBundle.sr.xlf
- src/Resources/translations/VerifyEmailBundle.tr.xlf
- src/Resources/translations/VerifyEmailBundle.uk.xlf
> Add missing target-language attr to all translations

- CHANGELOG.md
*July 12th, 2022*
- [#118](https://github.com/symfonycasts/verify-email-bundle/pull/118) - Add catalan translations - *@victormhg*
- [#121](https://github.com/symfonycasts/verify-email-bundle/pull/121) - Add missing target-language attr to all translations - *@bocharsky-bw*
_Generated by Git Released_
> [git-released] v1.11.0

- CHANGELOG.md
*October 4th, 2022*
- [#127](https://github.com/symfonycasts/verify-email-bundle/pull/127) - [translations] additional Polish translations - *@Flower7C3*
- [#125](https://github.com/symfonycasts/verify-email-bundle/pull/125) - drop symfony 4.4 support - *@jrushlow*
_Generated by Git Released_
> [git-released] v1.12.0

- .github/workflows/phpunit.yml
- .github/workflows/static.yaml
- psalm.xml
- Adds PHP 8.2 to test matrix
- Splits Static vs PHPUnit test config
- CI Housekeeping
> [ci] housekeeping

- CHANGELOG.md
*January 4th, 2023*
- [#131](https://github.com/symfonycasts/verify-email-bundle/pull/131) - Indonesian translation - *@priyadi*
- [#130](https://github.com/symfonycasts/verify-email-bundle/pull/130) - Add Dutch translations to exceptions - *@brentlobbezoo*
_Generated by Git Released_
> [git-released] v1.13.0

- src/Resources/translations/VerifyEmailBundle.de.xlf
> Missing german translations. Update VerifyEmailBundle.de.xlf 

- src/Model/VerifyEmailSignatureComponents.php
- tests/VerifyEmailTestKernel.php
public method signature changes are a non factor
> [ci] php-cs-fixer it up

- tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
- tests/FunctionalTests/VerifyEmailHelperFunctionalTest.php
- tests/IntegrationTests/VerifyEmailBundleAutowireTest.php
- tests/IntegrationTests/VerifyEmailServiceDefinitionTest.php
- tests/UnitTests/VerifyEmailHelperTest.php
- tests/VerifyEmailTestKernel.php
- remove legacy annotations
- remove legacy test methods
- adds missing property types
- uses constructor property promotion
> [2.x][tests] remove legacy tests and cleanup

- README.md
MakerBundle was updated - awhile ago - with new generated code for this bundle. This updates the docs to reflect that - the code was copied from following the README on a real project.
Cheers!
> Updating docs for latest generated code from MakerBundle

- src/Generator/VerifyEmailTokenGenerator.php
- src/Model/VerifyEmailSignatureComponents.php
- src/VerifyEmailHelper.php
- tests/VerifyEmailTestKernel.php
- use constructor property promotion where possible
- removes unneeded `interal` flag in test kernel
> [2.x] refactor to use php 8.3 features

- .gitignore
- phpunit.xml.dist
- tests/Acceptance/VerifyEmailAcceptanceTest.php
- tests/Functional/VerifyEmailHelperFunctionalTest.php
- tests/Integration/VerifyEmailBundleAutowireTest.php
- tests/Integration/VerifyEmailServiceDefinitionTest.php
- tests/Unit/Exception/VerifyEmailExceptionTest.php
- tests/Unit/Generator/VerifyEmailTokenGeneratorTest.php
- tests/Unit/Model/VerifyEmailSignatureComponentsTest.php
- tests/Unit/Util/VerifyEmailQueryTest.php
- tests/Unit/VerifyEmailHelperTest.php
- updates `phpunit.xml.dist` to latest (`9.6`) schema
- removes `Test` suffix from test directories (`tests/UnitTests` -> `tests/Unit`)
> [ci] update phpunit config to latest schema

- .php-cs-fixer.dist.php
> [ci] php-cs-fixer the php-cs-fixer config

- tests/Functional/VerifyEmailHelperFunctionalTest.php
> [tests] remove legacy test for validateEmailConfirmation

- src/Resources/translations/VerifyEmailBundle+intl-icu.nl.xlf
> Fix typo in nl translation

- composer.json
> Drop ext-json from composer.json
