- src/VerifyEmailHelper.php
- tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
The url generator returns the absolute path for a route by default. We need to sign the absolute URL. 
closes #3
> signs the absolute url

- composer.json
_only affects bundle development_
- ~fixed wrong use statements for `RoutingConfigurator`~ - no longer relevant
~and~
`doctrine/persistence` `1.3` is required by `symfony/framework-bundle` `dev-master`. `doctrine/orm` `2.7` uses `doctrine/persistence` `^1.2` where as `2.8-dev` uses `doctrine/persistence` `~1.2`, which blocks `1.3`. 
This PR essentially chooses to use the `master` branch of the `framework-bundle` with `orm 2.7` instead of using `framework-bundle 5.0.1` with `orm 2.8-dev`
```
- Updating doctrine/persistence (1.2.x-dev 43526ae => 1.4.x-dev f5cf0d5):  Checking out f5cf0d59f5
- Downgrading doctrine/orm (2.8.x-dev 3c91792 => 2.7.x-dev 70fb1ec):  Checking out 70fb1ecd78
- Removing symfony/framework-bundle (v5.0.1)
- Installing symfony/framework-bundle (dev-master 2f247eb): …
```
> [dev] use dev-master for the framework-bundle

- src/Model/VerifyEmailSignatureComponents.php
- src/VerifyEmailHelper.php
- src/VerifyEmailHelperInterface.php
- tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
- tests/FunctionalTests/VerifyEmailHelperFunctionalTest.php
- tests/UnitTests/VerifyEmailHelperTest.php
- `VerifyEmailSignatureComponents::class` `getSignature()` => `getSignedUrl()` - method returns the absolute signed url, not just the signature.
- `VerifyEmailHelper/Interface::class`:
- `generateSignature()`  args -
`array $extraParams` => `array $queryParams` - query params that will be signed, but not generated by the bundle.
- `isValidSignature()` args -
`string $signature` => `string $signedUrl` - we validate the complete url, not the signature
> refactor names throughout the codebase

- src/VerifyEmailHelper.php
- src/VerifyEmailHelperInterface.php
- tests/UnitTests/VerifyEmailHelperTest.php
`VerifyEmailSignatureComponents::class` has a method to retrieve the signature expiration
> removed helper method to get the expected lifetime of a signature

- .github/workflows/ci.yml
- composer.json
- psalm.xml
- Removes psalm's `MisplacedRequiredParam` issue which is no longer supported.
- Updates CI for Composer 2 usage
- CI runs for `php-cs-fixer` & `psalm` are forced to use PHP 7.4 until both packages fully support PHP 8
Bumps dev dependencies to versions that support PHP 8
- `doctrine/persistence`
- `php-cs-fixer`
- `psalm`
> PHP 8 support in CI / Dev

- CHANGELOG.md
- composer.json
- src/Model/VerifyEmailSignatureComponents.php
- src/Resources/translations/VerifyEmailBundle.en.xlf
- src/VerifyEmailHelper.php
- tests/UnitTests/Model/VerifyEmailSignatureComponentsTest.php
This PR resolves the long standing issue of possibly invalid expiration values. It all adds support for translating when a signature expires out of the box.
closes #39
> improve signature expiration support

- .github/workflows/ci.yml
Use ubuntu 1804 for tests that rely on PHP <7.4. Github released base image ubuntu-latest which uses ubuntu-20.04 - the 20.04 does not have PHP 7.0 - 7.3. Previously, ubuntu-latest was based on ubuntu-18.04
> [CI] run tests on ubuntu 18.04

- src/Resources/translations/VerifyEmailBundle+intl-icu.nl.xlf
Added Dutch translations. Because of the somewhat complex nature of the Dutch language (0 vs 1 vs many) I've chosen to use the `intl-icu` format as it (suppose to be/) is the new standard and has better support for the complex scenarios. And as the minimum requirements of the bundle are `symfony/*:^4.4` it should not be a problem. Also Christophe mentioned to it in https://github.com/SymfonyCasts/verify-email-bundle/pull/56#issuecomment-780758383. 
If we would refactor all translations in one go to the `icu-intl` format and first use the old notation, let me know I would adjust this PR.
As for the Dutchies who want to check this PR, I've used the 'rules' in https://taaladvies.net/taal/advies/vraag/511 to translate it (used in \SymfonyCasts\Bundle\VerifyEmail\Model\VerifyEmailSignatureCompo …
> Added Dutch translations (in intl-icu format)

- CHANGELOG.md
- src/Resources/translations/VerifyEmailBundle.pl.xlf
mirrors https://github.com/SymfonyCasts/reset-password-bundle/pull/149
Context:
`This link will expire in 1 year` which in Polish is `Link wygaśnie w ciągu 1 roku`
`This link will expire in 3 years` which in Polish is `Link wygaśnie w ciągu 3 lat`
`This link will expire in 5 years` which in Polish is `Link wygaśnie w ciągu 5 lat`
`This link will expire in 6 years` which in Polish is `Link wygaśnie w ciągu 6 lat`
`This link will expire in 17 years` which in Polish is `Link wygaśnie w ciągu 17 lat`
the same context applies for `month|months`, `day|days`, `hour|hours`, `minute|minutes`
> add Polish translations

- .github/workflows/ci.yml
- .php-cs-fixer.dist.php
- composer.json
- keeping `'phpdoc_to_comment' => false,` even though it contradicts the symfony rule set. This is an edge case introduced in https://github.com/SymfonyCasts/verify-email-bundle/commit/e587c86c1582052109471fc48cc61b6a40c93273
> [ci] upgrade php-cs-fixer 2.x -> 3.0

- README.md
This commit modifies example code to fix 'An email must have a "From" or a "Sender" header.'
> Fix 'An email must have a "From" or a "Sender" header.'

- phpunit.xml.dist
Prevents failing CI run for problems such as:
> [ci] ignore indirect deprecations

- CHANGELOG.md
- [#76](https://github.com/SymfonyCasts/verify-email-bundle/pull/76) - add missing return types for Symfony 6 support - *@jrushlow*
> [release] update changelog for 1.6.0

- .github/workflows/ci.yml
Symfony flex changed branch names to support PHP 8. This PR lets composer decide which version of flex is appropriate for CI and runs psalm against PHP 8.
> [ci] fix flex version & fix psalm

- composer.json
Symfony 6.0 uses `symfony/deprecation-contracts` @ `^3.0`, we need to allow `2.2` && `3.0` then let composer decide which can be installed based off of the PHP version. Otherwise reset-password cannot be used w/ Symfony 6+
> allow deprecation contracts 3.0

- CHANGELOG.md
*November 30th, 2021*
- [#90](https://github.com/SymfonyCasts/verify-email-bundle/pull/90) - allow deprecation contracts 3.0 - *@jrushlow*
> [release] prep for 1.7

- psalm.xml
Recently Psalm started failing with the next error:
```
ERROR: ConfigIssue - psalm.xml:4:5 - Attribute "totallyTyped" is deprecated and is going to be removed in the next major version (see https://psalm.dev/271)
totallyTyped="true"
------------------------------
1 errors found
------------------------------
```
More information about the deprecation is here: https://github.com/vimeo/psalm/blob/f72f2f6fbe27b00c1fd8cd3ff8214a2d68fea14a/docs/running_psalm/configuration.md#totallytyped
> Replace deprecated totallyTyped=true with errorLevel=1

- CHANGELOG.md
Howdy Verifiers!
Thanks to @bocharsky-bw and other contributors, we now have support for exception reason translations! French, Russian, and Ukrainian are provided out of the box. 
*February 23rd, 2022*
- [#109](https://github.com/symfonycasts/verify-email-bundle/pull/109) - [translations] Slovak - *@jrushlow*
- [#107](https://github.com/symfonycasts/verify-email-bundle/pull/107) - Translate exception reasons to French - *@PauchardThomas*
- [#106](https://github.com/symfonycasts/verify-email-bundle/pull/106) - Translate exception reasons to Russian - *@bocharsky-bw*
- [#105](https://github.com/symfonycasts/verify-email-bundle/pull/105) - Translate exception reasons to Ukrainian - *@bocharsky-bw*
- [#103](https://github.com/symfonycasts/verify-email-bundle/pull/103) - RFC: Add translations …
> [release] prep v1.9.0

- src/Resources/translations/VerifyEmailBundle.es.xlf
Let's make this bundle a bit more complete by adding Spanish translations to the exception messages
> Add Spanish translations to exceptions

- .github/workflows/ci.yaml
- composer.json
Assumes the following: 
- VerifyEmail `1.x` will be maintained through the end of 2024 (coincide w/ Symfony 5.4 EOL && PHP 8.2 EOL)
- VerifyEmail `1.x` will transition to security fixes only soon-ish. I believe this is safe considering the stability demonstrated since the bundles inception.
- VerifyEmail `2.x` will be the `default` branch for the repo, all new features will be merged into `2.x`. This would happen sometime _after_ we merge #157 
Changes: 
- bumps PHP minimum  `8.3`. When `1.x` reaches EOL in November-ish 2024 (EOL for Symfony 5.4). PHP 8.2 will be security fixes only. PHP `8.4` is due out 2024. Setting `8.3` as the minimum feels "bleeding-edge" but I think this is ok with the release cadence of PHP and our timing with a `2.x` branch.
- Dropping Symfony `5.x` with a minimum …
> [2.x] version bumps

- src/Util/VerifyEmailQueryUtility.php
- src/VerifyEmailHelper.php
- src/VerifyEmailHelperInterface.php
- tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
- tests/FunctionalTests/VerifyEmailHelperFunctionalTest.php
- tests/IntegrationTests/VerifyEmailBundleAutowireTest.php
- tests/IntegrationTests/VerifyEmailServiceDefinitionTest.php
- tests/UnitTests/Util/VerifyEmailQueryTest.php
- tests/UnitTests/VerifyEmailHelperTest.php
- add's a new `validateEmailConfirmationFromRequest()` to `VerifyEmailHelperInterface` & it's implementation.
- deprecates `validateEmailConfirmation()` in `VerifyEmailHelperInterface` & it's implementation.
- ~deprecates `VerifyEmailQueryUtility` as this is no longer needed in the new "fromRequest" helper method.~
- does _not_ deprecates the 3rd `$queryUtility` argument in the `VerifyEmailHelper::__construct()` method as this argument is not nullable`
- deprecates passing anything other than an instance of `UriSigner` as the `$uriSigner` argument in the `VerifyEmailHelper::__construct()` method.
- silences self deprecations (introduced by this PR) in tests using `@group legacy` annotations. This is basically our entire test suite. Work is already started in #159 that will remove these …
> [1.x] use `UriSigner::checkRequest()` to validate signatures using a `Request` object

- UPGRADING.md
- src/Factory/UriSignerFactory.php
- Adds `internal` & `final` docBlock to `UriSignerFactory`
- Refactor class to use constructor property promotion
- Adds `SensitiveParameter` attribute to `$secret` property. (Prevents stack trace leaks in PHP `>=8.2`)
- Init `UPGRADE.md` guide for BC changes coming in `v2.0`
The `UriSignerFactory` will no longer be needed in `v2.0`. The intent is to make this `internal` in `v2.0.0` then remove it in a later `v2.x` release. This should avoid having to deprecate it in `v2.0` then remove it in `v3.0` - while preserve BC for `v1.x`.
Precursor to #164
> [1.x] UriSigner to become internal in 2.x

- src/Factory/UriSignerFactory.php
- src/Resources/config/verify_email_services.xml
- src/VerifyEmailHelper.php
- tests/IntegrationTests/VerifyEmailServiceDefinitionTest.php
- We can inject the `UriSigner` directly into `VerifyEmailHelper` instead of using a factory to pick the correct service.
- We can remove xor deprecate the `UriSignerFactory` in a separate PR for `2.0` depending on what we do with #165 
- replace `@final` docBlock tag with `final` class keyword in `UriSignerFactory`
> [2.x] inject UriSigner directly in the VerifyEmailHelper

- UPGRADING.md
- src/Model/VerifyEmailSignatureComponents.php
- Change `$generatedAt` from being an _optional_ `null|int` constructor parameter to a _required_ `int` parameter when instantiating a `VerifyEmailSignatureComponents` instance
- Removes associated deprecation when passing `null` to the constructor
> [2.x] generatedAt is now required

- UPGRADING.md
- src/Model/VerifyEmailSignatureComponents.php
The `VerifyEmailSignatureComponents` `$generatedAt` property is always an `int` - we no longer need to throw a `LogicException` if the value is `null` in:
- `getExpirationMessageKey()`
- `getExpirationMessageData()`
- `getExpiresAtIntervalInstance()`
Consumers of this class do not need surround these methods with a `try`/`catch(\LogicException)` block.
> [2.x] remove potential `LogicException` from translation methods

- README.md
https://github.com/symfony/maker-bundle/pull/1464 changes `RegistrationController` to use constructor property promotion. Let's reflect that in the readme.
> RegistrationController uses constructor property promotion

- CHANGELOG.md
*March 16th, 2024*
* [#165](https://github.com/symfonycasts/verify-email-bundle/pull/165) - UriSignerFactory to become internal in 2.x - *@jrushlow*
* [#157](https://github.com/symfonycasts/verify-email-bundle/pull/157) - use `UriSigner::checkRequest()` to validate signatures using a `Request` object - *@jrushlow*
> [release] v1.17.0

- UPGRADING.md
- src/Model/VerifyEmailSignatureComponents.php
refs: #177
```
87     Method SymfonyCasts\Bundle\VerifyEmail\Model\VerifyEmailSignatureComponents::getExpirationMessageData() return type has no value type specified in iterable type array.
```
> typehint array shape for `getExpirationMessageData()` return value

- UPGRADING.md
- src/VerifyEmailHelperInterface.php
refs: #177 
```
34     Method SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelperInterface::generateSignature() has parameter $extraParams with no value type specified in iterable type array.
```
> typehint array shape for generateSignature()'s `$extraParams`

- UPGRADING.md
- src/DependencyInjection/SymfonyCastsVerifyEmailExtension.php
- src/Resources/config/verify_email_services.xml
- src/VerifyEmailHelper.php
- tests/Functional/VerifyEmailHelperFunctionalTest.php
- tests/Integration/VerifyEmailServiceDefinitionTest.php
- tests/Unit/VerifyEmailHelperTest.php
The `VerifyEmailQueryUtil` is no longer needed by the helper. Let's stop requiring it as a constructor argument.
> [2.x] stop passing QueryUtil to Helper constructor

- src/Factory/UriSignerFactory.php
This class is a "legacy" class, but became internal in 2.0 - so we should wait at least 1 .minor release before removing it. In the meantime, we can remove the LegacyUriSigner return type as this class is no longer available.
refs #177
> fix return signature for `createUriSigner`

- UPGRADING.md
- src/Exception/VerifyEmailRuntimeException.php
- src/Generator/VerifyEmailTokenGenerator.php
- src/Model/VerifyEmailSignatureComponents.php
- src/VerifyEmailHelper.php
- `VerifyEmailTokenGenerator::createToken()` now throws a `VerifyEmailRuntimeException` if `json_encode()` throws an error when encoding `$userId` & `$email`
- `VerifyEmailSignatureComponents::_multiple_methods_` & `VerifyEmailHelper::generateSignatur()` throw a `VerifyEmailRuntimeException` when unable to create a `DateTimeImmutable` instance
refs #177
> throw exception when unable to create DateTimeImmutable instance or encode json

- src/Resources/translations/VerifyEmailBundle.fr.xlf
The error messages mention a reset (🇫🇷 "réinitialisation") link—maybe from the ResetPasswordBundle? Updated it to "verification" (🇫🇷 "vérification").
> Fix typos in FR translations

- phpstan-baseline.neon
- tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
- tests/FunctionalTests/VerifyEmailHelperFunctionalTest.php
https://github.com/symfony/symfony/pull/59022 changed how signed urls are encoded. This change to the tests is required for 7.3+.
> minor: fix tests for url-safe signed urls
